research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

newsletter_task:
  description: >
    Create a newsletter about {topic} that highlights the key developments and insights.
  expected_output: >
    A well-structured newsletter that includes an introduction, key points, and a conclusion.
  agent: newsletter_writer

newsletter_edit_task:
  description: >
    Review and edit the newsletter about {topic} to ensure clarity and engagement.
  expected_output: >
    A polished version of the newsletter with improvements in structure, clarity, and engagement.
  agent: newsletter_editor
