demographic_research:
  description: >
    Research nutritional needs for an individual with the following demographics:
      - Age: {user_info['age']}
      - Gender: {user_info['gender']}
      - Height: {user_info['height']}
      - Weight: {user_info['weight']}
      - Activity Level: {user_info['activity_level']}
      - Goals: {user_info['goals']}
      
    Provide detailed nutritional requirements including:
      1. Caloric needs (basal and adjusted for activity)
      2. Macronutrient distribution (proteins, carbs, fats)
      3. Key micronutrients particularly important for this demographic
      4. Hydration requirements
      5. Meal timing and frequency recommendations
  expected_output: >
    A comprehensive nutritional profile with scientific rationale
  agent: nutritionist

medical_analysis:
  description: >
    Analyze the following medical conditions and medications, then provide dietary modifications:
      - Medical Conditions: {user_info['medical_conditions']}
      - Medications: {user_info['medications']}
      - Allergies/Intolerances: {user_info['allergies']}
      
    Consider the baseline nutritional profile and provide:
      1. Specific nutrients to increase or limit based on each condition
      2. Food-medication interactions to avoid
      3. Potential nutrient deficiencies associated with these conditions/medications
      4. Foods that may help manage symptoms or improve outcomes
      5. Foods to strictly avoid
  expected_output: >
    A detailed analysis of medical nutrition therapy adjustments
      agent: medical_specialist

diet_plan:
  description: >
    Create a detailed, practical diet plan incorporating all information:
      - User's Food Preferences: {user_info['food_preferences']}
      - Cooking Skills/Time: {user_info['cooking_ability']}
      - Budget Constraints: {user_info['budget']}
      - Cultural/Religious Factors: {user_info['cultural_factors']}
      
    Develop a comprehensive nutrition plan that includes:
      1. Specific foods to eat daily, weekly, and occasionally with portion sizes
      2. A 7-day meal plan with specific meals and recipes
      3. Grocery shopping list with specific items
      4. Meal preparation tips and simple recipes
      5. Eating out guidelines and suggested restaurant options/orders
      6. Supplement recommendations if necessary (with scientific justification)
      7. Hydration schedule and recommended beverages
      8. How to monitor progress and potential adjustments over time
  expected_output: >
    A comprehensive, practical, and personalized nutrition plan
  agent: diet_planner