research_task:
  description: >
    Conduct a thorough research about {topic} and provide a comprehensive summary
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A detailed summary of the research findings, including key points, trends and insights related to {topic}.
  agent: researcher
